apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "redis.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "redis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          args:
            {{- toYaml .Values.redis.args | nindent 12 }}
          ports:
            - name: {{ .Values.redis.ports.redis.name }}
              containerPort: {{ .Values.redis.ports.redis.containerPort }}
              protocol: TCP
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: {{ .Values.redis.volumeMounts.data.name }}
              mountPath: {{ .Values.redis.volumeMounts.data.mountPath }}
            {{- end }}
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: {{ .Values.redis.env.ALLOW_EMPTY_PASSWORD | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.exporter.enabled }}
        - name: redis-exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          args:
            {{- toYaml .Values.exporter.args | nindent 12 }}
          ports:
            - name: {{ .Values.exporter.ports.metrics.name }}
              containerPort: {{ .Values.exporter.ports.metrics.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: {{ .Values.redis.volumeMounts.data.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName | default (include "redis.fullname" .) }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-svc
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.ports.redis.name }}
      port: {{ .Values.service.ports.redis.port }}
      targetPort: {{ .Values.service.ports.redis.targetPort }}
      protocol: TCP
    {{- if .Values.exporter.enabled }}
    - name: {{ .Values.service.ports.metrics.name }}
      port: {{ .Values.service.ports.metrics.port }}
      targetPort: {{ .Values.service.ports.metrics.targetPort }}
      protocol: TCP
    {{- end }}
---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName | default (include "redis.fullname" .) }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
{{- end }}

