apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-whisper-vllm
  namespace: argocd # Default namespace for ArgoCD applications
spec:
  project: default
  source:
    repoURL: https://github.com/Soban-cd/tfhelm.git # Placeholder: Replace with your Git repository URL
    path: helm_charts/whisper-vllm
    targetRevision: HEAD # Placeholder: Replace with your target branch or tag
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: reva-chat # Target namespace for deployment, adjust if needed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

