apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-audio-enhancer
  namespace: argocd # Default namespace for ArgoCD applications
spec:
  project: default
  source:
    repoURL: YOUR_GIT_REPO_URL # Placeholder: Replace with your Git repository URL
    path: helm_charts/audio-enhancer
    targetRevision: HEAD # Placeholder: Replace with your target branch or tag
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: reva-chat # Target namespace for deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

