apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Soban-cd/tfhelm.git
    targetRevision: HEAD
    path: argocd_helm_package/argocd_applications/apps  # Folder containing child Application YAMLs
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  info:
    - name: type
      value: app-of-apps